### ISSUE TITLE
Cannot download file(s) from compute session

### ISSUE THREAD

**Issue by adrysn** [lablup/backend.ai-client-py#27]
`backend.ai download <sess-id> <filepath>` command is broken with following traceback:

```
Traceback (most recent call last):c51362187f653ee5745d6906b...
  File "/Users/adrysn/.pyenv/versions/playground/bin/backend.ai", line 11, in <module>
    sys.exit(main())
  File "/Users/adrysn/.pyenv/versions/3.7.0/envs/playground/lib/python3.7/site-packages/ai/backend/client/cli/__init__.py", line 104, in main
    args.function(args)
  File "/Users/adrysn/.pyenv/versions/3.7.0/envs/playground/lib/python3.7/site-packages/ai/backend/client/cli/__init__.py", line 40, in wrapped
    handler(args)
  File "/Users/adrysn/.pyenv/versions/3.7.0/envs/playground/lib/python3.7/site-packages/ai/backend/client/cli/files.py", line 44, in download
    kernel.download(args.files, show_progress=True)
  File "/Users/adrysn/.pyenv/versions/3.7.0/envs/playground/lib/python3.7/site-packages/ai/backend/client/base.py", line 79, in _caller
    return self._handle_response(resp, gen)
  File "/Users/adrysn/.pyenv/versions/3.7.0/envs/playground/lib/python3.7/site-packages/ai/backend/client/base.py", line 37, in _handle_response
    meth_gen.send(resp)
  File "/Users/adrysn/.pyenv/versions/3.7.0/envs/playground/lib/python3.7/site-packages/ai/backend/client/kernel.py", line 191, in _download
    total=resp.stream_reader.total_bytes,
AttributeError: 'Response' object has no attribute 'stream_reader'
```

Meanwhile, downloading from vfolders is working.

**Comment by adrysn** [comment]
mis-commit without reference issue number:
https://github.com/lablup/backend.ai-client-py/commit/00efd8c60f9ac8e906f698dc0f743cfa8af74038

**Comment by adrysn** [comment]
I fixed minor issues with the current download method. I think it is working now.
